const MODAL_BODY_TYPES = {
  CATEGORY: "CATEGORY",
  GENRE: "GENRE",

  DEFAULT: "",
};

const RIGHT_DRAWER_TYPES = {
  NOTIFICATION: "NOTIFICATION",
};

const CONFIRMATION_MODAL_CLOSE_TYPES = {
  CATEGORY: "CATEGORY",
  GENRE: "GENRE",
};
export { MODAL_BODY_TYPES, RIGHT_DRAWER_TYPES, CONFIRMATION_MODAL_CLOSE_TYPES };
