 const MODAL_BODY_TYPES = {
  USER_DETAIL: "USER_DETAIL",
  CATEGORY: "CATEGORY",
  PRODUCT: "PRODUCT",
  MEASURE: "MEASURE",
  DEPARTMENT: "DEPARTMENT",
  USER: "USER",
  STORE: "STORE",
  CONFIRMATION: "CONFIRMATION",
  SEND_RAW_PRODUCT: "SEND_RAW_PRODUCT",
  SEND_VARKA_PRODUCT: "SEND_VARKA_PRODUCT",
  DEFAULT: "",
};

 const RIGHT_DRAWER_TYPES = {
  NOTIFICATION: "NOTIFICATION",
};

 const CONFIRMATION_MODAL_CLOSE_TYPES = {
  CATEGORY: "CATEGORY",
  PRODUCT: "PRODUCT",
  MEASURE: "MEASURE",
  DEPARTMENT: "DEPARTMENT",
  USER: "USER",
  RAWPRODUCTSTORE: "RAWPRODUCTSTORE",
};
export {MODAL_BODY_TYPES,RIGHT_DRAWER_TYPES,CONFIRMATION_MODAL_CLOSE_TYPES}